# docker-compose -f compose.yml up --build

services:
  text-rpg:
    image: text-rpg
    container_name: text-rpg
    restart: unless-stopped
    user: "1000:1000"
    #environment:
    #  - PUID=1000
    #  - PGID=1001
    volumes:
      - ${HOME}/Docker/text-rpg:/data