---
username: "@XXX:matrix.org"
password: "XXX"
rooms:
  - "XXX"
  - "XXX"
gemini_api_key: "XXX"
groq_api_key: "XXX"
openai_api_key: "XXX"
models: # optional - prioritise what models to try and in what order
  #- groq/compound
  - gemini-2.5-flash-lite
  - openai/gpt-oss-120b
image_generation_enabled: true